- apps/mitt-konto/index.html
> Add viewport

- packages/ksf-login/src/JanrainSSO.js
This reverts commit 68b79a1212f1a597d612287f6ea705faa650840c.
> Revert "Enable SSO logs"

- packages/ksf-login/src/KSF/Login/View.purs
> Set password changes to state

- packages/ksf-navbar/src/KSF/Navbar/Component.purs
> Hide collapsed menu when logging out

- packages/ksf-login/src/KSF/Login/Component.purs
- packages/ksf-login/src/KSF/Login/Facebook/Success.purs
See #25 for context. This is pretty much the same, but for facebook.
Fix #22
> Do logoutFacebook only if we've had a facebook login

- packages/persona/package.json
- packages/persona/src/Persona.js
- packages/persona/src/Persona.purs
- yarn.lock
Adds the `/users/{uuid}/gdpr` interaction to Persona.
Fix #35
> Add usersUuidGdprPut

- apps/mitt-konto/src/MittKonto/Main.purs
- packages/ksf-alert/src/KSF/Alert/Component.purs
- packages/ksf-button/src/KSF/Button/Component.purs
- packages/ksf-description-list/src/KSF/DescriptionList/Component.purs
- packages/ksf-footer/src/KSF/Footer/Component.purs
- packages/ksf-input-field/src/KSF/InputField/Component.purs
- packages/ksf-login/src/KSF/Login/Component.purs
- packages/ksf-login/src/KSF/Login/View.purs
- packages/ksf-navbar/src/KSF/Navbar/Collapsed/Component.purs
- packages/ksf-navbar/src/KSF/Navbar/Component.purs
- packages/ksf-profile/src/KSF/Profile/Component.purs
- packages/ksf-subscription/src/KSF/Subscription/Component.purs
- packages/react-basic-extended/src/React/Basic/Extended.purs
- psc-package.json
> Upgrade react-basic

- apps/prenumerera/src/Prenumerera/PaymentSelect.purs
- psc-package.json
> Use psc-package release psc-0.12.1-20181218

- apps/mitt-konto/resources/mitt-konto.less
- apps/mitt-konto/src/MittKonto/Main.purs
- apps/prenumerera/src/Prenumerera/PaymentSelect.purs
- packages/ksf-subscription/src/KSF/Subscription/Component.purs
- packages/ksf-subscription/src/KSF/Subscription/View.purs
- packages/persona/src/Persona.purs
> Subscription ui adjustments

- packages/ksf-registration/src/KSF/Registration/Component.purs
- packages/ksf-registration/src/KSF/Registration/Registration.less
Minor fixes:
- increase font size in input fields
- add validation message to password field
- set type of email input to "email"
> Registration form fixes

- packages/ksf-login/src/KSF/Login/Component.purs
- packages/ksf-login/src/KSF/Login/View.purs
- packages/ksf-registration/src/KSF/Registration/Component.purs
This was calling the wrong `prop`!
> Fix onRegisterCancelled

- apps/elections/assets/less/app.less
- apps/elections/assets/less/parliament.less
- apps/elections/assets/less/parties.less
- apps/elections/assets/less/table.less
- apps/elections/components/App.js
- apps/elections/components/Parliament.js
- apps/elections/components/TestParties.js
- apps/elections/package.json
- yarn.lock
Parliament svg with dummy data
> Parliament svg

- packages/ksf-navbar/src/KSF/Navbar/View.purs
> Update customer service open hours

- apps/elections/components/App.js
- apps/elections/components/Backend.js
- apps/elections/components/Table.js
- apps/elections/package.json
- yarn.lock
Currently just hardcodes fetching of area `001` as we don't have a selector.
> Load candidates table data from the backend API

- apps/elections/components/App.js
- apps/elections/components/AreaPicker.js
- apps/elections/components/Backend.js
- apps/elections/package.json
Adds an area picker with all the logic for loading areas from the backend and respond to user interaction sensibly. Only misses some visual tweaks and Swedish labels.
#67 have to be merged first
> Area picker

- apps/elections/assets/less/app.less
- apps/elections/assets/less/status.less
- apps/elections/components/App.js
- apps/elections/components/Status.js
- apps/elections/package.json
- yarn.lock
> Add vote counting status pie-chart

- apps/elections/assets/less/app.less
- apps/elections/assets/less/chart.less
- apps/elections/assets/less/parliament.less
- apps/elections/assets/less/parties.less
- apps/elections/assets/less/selectors.less
- apps/elections/components/App.js
- apps/elections/components/AreaPicker.js
- apps/elections/components/Backend.js
- apps/elections/components/Chart.js
- apps/elections/components/Parliament.js
- apps/elections/components/TestParties.js
Added party chart and some other assorted fixes
> Party chart

- apps/elections/assets/less/parties.less
- apps/elections/assets/less/table.less
- apps/elections/components/Table.js
1. Sorted by votes by default + nicer indicator for sorted column
2. Added a square with the party color
3. Statuses different colors
- Smaller font overall
- Something else I probably forgot to mention
> Table improvements

- apps/elections/components/App.js
- apps/elections/components/Backend.js
Along with https://git.ksfmedia.fi/taco/election-backend/merge_requests/29 this makes the data much more interesting
> Get area data when the selection changes (and on startup)

- apps/elections/components/Table.js
- apps/elections/package.json
- yarn.lock
Added react-device-detect
Hidden some cols for mobiles
Changed order of first name and last name
> Hide some cols on mobile.

- apps/elections/assets/less/parliament.less
- apps/elections/components/Parliament.js
Added the text "Riksdagens fördelning just nu" to the parliament component.
> Add label text to parliament component

- apps/elections/components/AreaPicker.js
- apps/elections/components/Table.js
Combined first name and last name in one cell to save space and shrunk some other cells.
Also fixed some faulty texts.
> Combine names and shrink some columns.

- apps/elections/assets/less/chart.less
- apps/elections/assets/less/table.less
- apps/elections/components/App.js
- apps/elections/components/Chart.js
- apps/elections/components/Table.js
- apps/elections/package.json
- yarn.lock
Redesign of chart, some layout improvements on the table, implemented HashRouter (although not doing anything useful with it yet)
> Multiple fixes all over the place

- apps/elections/assets/less/app.less
- apps/elections/assets/less/areainfo.less
- apps/elections/components/App.js
- apps/elections/components/AreaInfo.js
Add AreaInfo component that shows name and vote count status of selected area.
> Add AreaInfo component

- apps/elections/assets/less/app.less
- apps/elections/assets/less/timestamp.less
- apps/elections/components/App.js
- apps/elections/components/Timestamp.js
- apps/elections/package.json
I've placed it in the opposite corner to the status pie, mirroring its
css, but some improvement to it would be nice.
> Add timestamp (timeago)

- apps/elections/.env.development
- apps/elections/assets/less/parliament.less
- apps/elections/components/App.js
> Let's get colors on the parliament

- apps/elections/components/App.js
How about something like this?
> set country data in state

- apps/elections/components/App.js
- apps/elections/index.js
> Add option to display app in compact mode

- apps/elections/components/App.js
> Fix styles for mobile

- apps/elections/components/Backend.js
The results of all calls are now implicitly saved, the cache can be
cleared by calling `Backend.memoizer.clear()`
> Memoize calls to backend

- apps/elections/components/Backend.js
This reverts commit a777b67e5b94f065a9985a32269a27adc275422c.
> Revert "Memoize calls to backend (#92)"

- less/ksf-utils.less
- packages/async-wrapper/src/AsyncWrapper.purs
And .tiny-spinner to ksf-utils
> Add AsyncWrapper

- apps/elections/.env.development
- apps/elections/assets/less/selectors.less
- apps/elections/assets/less/status.less
- apps/elections/assets/less/timestamp.less
- apps/elections/components/App.js
- apps/elections/components/Timestamp.js
- apps/elections/index.js
- packages/grid/src/KSF/Grid.purs
/eu gives result service without parliament chart and little more compact  count status and timestamp
> EU mode for election sservice

- apps/mitt-konto/resources/mitt-konto.less
- apps/mitt-konto/src/MittKonto/Main.purs
- packages/ksf-navbar/src/KSF/Navbar/Navbar.less
- packages/ksf-navbar/src/KSF/Navbar/View.purs
> Mitt konto frontpage changes

- apps/app-article/src/components/related-articles.js
> change property name according to the API

- package.json
- packages/ksf-subscription/src/KSF/Subscription/Component.purs
- packages/temporary-address-change/src/KSF/TemporaryAddressChange/Component.purs
Adds
- validation to zip input (only digits accepted)
- city input field
#120
> Fix temporary address change inputs

- packages/ksf-subscription/src/KSF/Subscription/Component.purs
Also, show "billing period ends" in cancelled subscriptions too.
> Change "next billing date" to "billing period ends"

- apps/app-article/src/components/article-details.js
> fixed author not showing on the article

- apps/app-article/src/components/loading.js
- apps/app-article/src/index.css
> center loading icon

- LICENSE
- apps/app-article/package.json
- apps/app-article/src/App.js
- less/Login.less
- packages/user/.gitignore
- packages/user/README.md
- packages/user/index.js
- packages/user/package.json
- yarn.lock
Make `User` standalone-npm-package-compatible
TODO:
> WIP: User npm

- packages/user/package.json
- packages/user/src/User/JS.purs
- packages/user/src/User/Login/Google/Google.js
Fixes the issue that `jsLogout` returns a function.
```Javascript
// Current (kinda broken) behaviour:
logout(() => console.log("logged out!"))();
// Fixed behaviour:
logout(() => console.log("logged out!"));
> Fix jsLogout

- packages/user/package.json
New `user` published here https://www.npmjs.com/package/@ksf-media/user
> Bump @ksf-media/user version

- apps/app-article/package.json
- apps/app-article/src/ads.txt
Adds ads.txt to the build of app-article
> Add ads.txt to build

- packages/components/src/Persona.purs
- packages/components/src/Profile/Component.purs
- packages/components/src/Registration/Component.purs
- packages/components/src/Subscription/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
- packages/components/src/ValidatableForm.purs
- packages/user/package.json
- packages/user/src/User/User.purs
- yarn.lock
Adds temporary name input and shows it wherever the delivery address is shown.
> Add temporary name (c/o) to temporary address change

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/prenumerera/src/Prenumerera/Main.purs
- packages/user/README.md
- packages/user/package.json
- packages/user/src/User/JS.purs
- packages/user/src/User/Login.purs
- packages/user/src/User/User.purs
The `jsLogout` now takes to callbacks:
1) on success callback
2) on failure callback
> Logout callbacks

- apps/app-article/src/App.js
- apps/app-article/src/index.html
wait till article content is finished and all dom element is completed than call the function to load ads
> load ads when all dom element finished

- apps/app-article/src/App.js
added new field to google tag manager, changed byline property
> add missing fidelds to google tag

- apps/app-article/src/index.css
> remove hyphens

- apps/app-article/src/components/related-articles.js
- apps/app-article/src/index.css
> enhance layout

- less/Footer.less
- less/InputField.less
- packages/components/src/Registration/Component.purs
- packages/user/src/User/Login.purs
- Don't treat username input in login form as email
- Don't send empty (unvalid) login form data to server
- Fix #210
- Fix #211
> Minor ui fixes

- apps/app-article/src/App.js
> add new attributes for gtm

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- packages/user/package.json
- packages/user/src/User/Login.purs
- packages/user/src/User/Login/Google/Google.js
- packages/user/src/User/Login/Google/Google.purs
> Fix Google login

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina/.build-size-sha256
- hooks/pre-commit
- packages/components/src/Bottega.js
- packages/components/src/Bottega.purs
- packages/components/src/OpenApiClient.js
- packages/components/src/OpenApiClient.purs
- packages/components/src/Persona.js
- packages/components/src/Persona.purs
Just moving the copy-pasted code to a shared module and improve logging a bit.
> Make OpenApiClient module with utilities for using generated clients

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina/.build-size-sha256
- apps/vetrina/src/Vetrina/Main.purs
- packages/components/src/Bottega.purs
- packages/components/src/OpenApiClient.purs
- packages/components/src/Persona.purs
- packages/user/package.json
- packages/user/src/User/User.purs
- yarn.lock
Catch canceled orders and show the `NewPurchase` view.
Also fix some warnings.
> Canceled orders

- apps/app-article/src/index.css
break long words into new line and add hyphenate
> break long words and add hyphenation

- apps/app-article/src/index.css
we concluded to remove for now the hyphenation of words!
> remove hyphen for for now

- apps/mitt-konto/.build-size-sha256
- apps/mitt-konto/spago.dhall
- apps/prenumerera/.build-size-sha256
- apps/prenumerera/spago.dhall
- apps/vetrina/.build-size-sha256
- apps/vetrina/.env.development
- apps/vetrina/package.json
- apps/vetrina/spago.dhall
- apps/vetrina/src/Vetrina/Main.js
- apps/vetrina/src/Vetrina/Main.purs
- package.json
- packages.dhall
- packages/components/src/Api/Package.purs
- packages/components/src/JSError.js
- packages/components/src/JSError.purs
- packages/components/src/Product.purs
- packages/components/src/Sentry.js
- packages/components/src/Sentry.purs
- yarn.lock
Add sentry integration and send events from obvious places in Vetrina.
> Sentry tryout

- apps/vetrina/.build-size-sha256
- apps/vetrina/src/Vetrina/Main.purs
- packages/components/src/Product.purs
Inform the user if they already have a subscription for the product they're trying to purchase
> Check user entitlements

- apps/mitt-konto/.build-size-sha256
- less/Subscription.less
- packages/components/src/Subscription/Component.purs
* Rename pauseContainer to actionsContainer
* Rename pauseContainer associated css class
Fixes #277.
> Refactor Subscription component

- apps/app-article/src/components/article-content.js
- apps/app-article/src/index.css
show footnote and question according to #293
> render footnote and question according to specs

- apps/mitt-konto/.build-size-sha256
- apps/vetrina/.build-size-sha256
- packages/components/src/Persona.purs
Don't send empty cache-control header
> Fix cache control

- apps/podcasts/src/App.js
- apps/podcasts/src/less/main.less
- Nicer loading behaviour
- Wrapped all less inside of `.pod-app{}`
> Podcasts loading

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina/.build-size-sha256
- apps/vetrina/index.js
- apps/vetrina/src/Vetrina/Main.purs
- apps/vetrina/src/Vetrina/Purchase/Completed.purs
- apps/vetrina/src/Vetrina/Purchase/NewPurchase.purs
- apps/vetrina/src/Vetrina/Purchase/SetPassword.purs
- apps/vetrina/src/Vetrina/Types.purs
- less/vetrina.less
- packages/components/src/InputField/Component.purs
Add #325.
Also separate the landing screen into its own module (`NewPurchase`). Sorry, the refactoring is huge.
> Handle logged in users

- apps/podcasts/README.md
- apps/podcasts/src/App.js
- apps/podcasts/src/Track.js
- apps/podcasts/src/less/main.less
- Nicer loading behaviour
- Nicer podcast navigation
> Podcasts loadingscreen

- less/Vetrina.less
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Purchase/Completed.purs
- remove `body` rule from vetrina css
- fix typo in `Completed` view
> Small vetrina fixes

- less/Spinner.less
- less/Vetrina.less
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Vetrina.purs
> Fix spinner

- packages/vetrina/src/Vetrina/Vetrina.purs
> Set user to state before making order

- packages/components/src/Bottega.purs
- packages/user/src/User/User.purs
- packages/vetrina/src/Vetrina/Purchase/SubscriptionExists.purs
- packages/vetrina/src/Vetrina/Vetrina.purs
Also fix setting state in `mkPurchase`: don't try to set the state multiple times -> just do it once -> no possibility of react getting confused
Fix #299
NOTE/TODO: We could probably have one component to execute layout:
- headline
- text
- button
> Add view for existing subscription

- packages/vetrina/package.json
Adds:
- better handling for invalid credentials on login
- view for subscription exists case
> Bump vetrina

- apps/app-article/src/index.css
- scripts/app/gamAppAds.js
A bigger headline and footer for ads to make them more distinct from editorial content.
> bigger ad marker

- package.json
- yarn.lock
Should be now able to minify es6 as well.
> Replace uglify-js with uglify-es

- apps/vetrina-staging/.build-size-sha256
- less/Vetrina.less
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs
- change subscribe button text to be more clear
- add link to prenumerera
> Vetrina fixes

- apps/mitt-konto/.build-size-sha256
- packages/components/src/Subscription/Component.purs
Let's not treat user input failures as errors in Sentry.
> Nerf sentry errors

- apps/mitt-konto/.build-size-sha256
- less/Profile.less
- packages/components/src/Profile/Component.purs
Fix #306
Also move the submit button to the bottom of the profile editing form.
> Add ability to retry after profile editing error

- packages/components/src/Subscription/Component.purs
> Show sub actions on success

- apps/app-article/.build-size-sha256
- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina-staging/.build-size-sha256
- packages/components/src/Api/Subscription.purs
- packages/components/src/Persona.purs
- packages/components/src/Subscription/Component.purs
Show payment method for each subscription
> Add payment method

- packages/components/src/TemporaryAddressChange/Component.purs
> Allow duration of temporary address change to be seven days

- packages/components/src/Spinner.purs
- packages/vetrina/src/Vetrina/Vetrina.purs
* Add a function Spinner.loadSpinnerWithMessage which displays a message along with the spinner
> Display a message when redirecting to Nets in Vetrina (#422)

- apps/vetrina-test/index.js
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Products.purs
- packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs
- packages/vetrina/src/Vetrina/Types.purs
> Add name to product, pre-select first item on products array

- less/TemporaryAddressChange.less
- packages/components/src/TemporaryAddressChange/Component.purs
This was because of basscss for some weird reason
> Fix form fields not aligning nicely

- packages/components/src/Persona.purs
- packages/components/src/Subscription/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
- packages/components/src/TemporaryAddressChange/DropDown.purs
- packages/components/src/TemporaryAddressChange/Types.purs
- packages/user/package.json
- packages/vetrina/package.json
- yarn.lock
> Add a dropdown menu for selecting a previously used temporary address

- apps/mitt-konto/.build-size-sha256
- deploy.rb
* Add PRODUCTION_BOTTEGA_URL env var
> Fix deploy.rb

- apps/app-article/src/App.js
Reverts KSF-Media/affresco#451
for now let it show as previously, need to investigate more this!
> Revert "change text"

- apps/mitt-konto/src/MittKonto/Main.purs
- images/backwards.svg
- less/mitt-konto.less
> Back link for payments page

- apps/app-article/.build-size-sha256
- apps/mitt-konto/.build-size-sha256
- less/AccountEdit.less
- less/mitt-konto.less
This should make **app article** build again. Also it removes some unused CSS rules.
> Fix mitt-konto style

- apps/mitt-konto/src/MittKonto/AccountEdit.purs
- apps/mitt-konto/src/MittKonto/IconAction.purs
- apps/mitt-konto/src/MittKonto/Main.purs
- less/AccountEdit.less
- less/Components.less
- less/IconAction.less
- less/mitt-konto.less
- packages/components/src/IconAction.purs
Adds `IconAction` component. We are using the same style of `<icon> <description>` links/actions in a couple of places in mitt konto (and underlying components) so this will make it a bit nicer. This also makes a clear distinction of css classes and module responsibilities regarding these actions.
> Add IconAction component

- packages/vetrina/package.json
- packages/vetrina/src/Tracking.js
- packages/vetrina/src/Tracking.purs
- yarn.lock
runEffectFn didn't work for some reason for the analytics, switched back to runFn
> use runFn instead of runEffectFn with transaction analytics event

- apps/vetrina-test/index.js
- apps/vetrina-test/package.json
- apps/vetrina-test/test/Main.purs
- less/Vetrina.less
- packages/components/src/Persona.purs
- packages/components/src/ValidatableForm.purs
- packages/vetrina/spago.dhall
- packages/vetrina/src/Vetrina/Purchase/AccountForm.purs
- packages/vetrina/src/Vetrina/Purchase/InsufficientAccount.purs
- packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs
- packages/vetrina/src/Vetrina/Vetrina.purs
When facing `insufficient account` error from Bottega, show form asking contact information (name, address).
> Ask account details

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Types.purs
- apps/mitt-konto/src/MittKonto/Main/Views.purs
- apps/mitt-konto/src/MittKonto/Main/Views/LoginView.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView.purs
- less/Components.less
- less/Navbar.less
- less/Search.less
- less/mitt-konto.less
- packages/components/src/Api.purs
- packages/components/src/Navbar/Component.purs
- packages/components/src/Persona.purs
- packages/components/src/Search.purs
- packages/user/package.json
- packages/user/spago.dhall
- packages/user/src/User/User.purs
- packages/vetrina/package.json
- yarn.lock
Adds a new type, Credentials, which is used for auth credential
storage instead of reusing LoginResponse which is used by Persona.
> User search and personating interface for admin users

- apps/app-article/src/App.js
set auth token and uuid to cookie, for able to be accesible by native mobile app
> add token and uui to coockie to access from native side

- apps/app-article/src/App.js
> add new logout handler for logout

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Wrappers/RouteWrapper.purs
Also, use Redirect to root when route is not supported, instead of
just rendering mitt konto front page.
> Fix no match route

- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- less/Subscription.less
* Fix layout of update actions
Related to #469 .
> Fix MittKonto.Main.UserView.Subscription

- packages/vetrina/package.json
- yarn.lock
No API changes between this and 5.30.0.
> Upgrade @sentry/browser to 6.2.1

- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
> Show credit card update action in digital only subscriptions

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Views/CreditCardUpdateView.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- packages/components/src/Bottega/Models/CreditCard.purs
- packages/components/src/Tracking.js
- packages/components/src/Tracking.purs
> Add analytics events for credit card update

- apps/corona-banner/package.json
> Downgrade Parcel

- apps/mitt-konto/src/MittKonto/Main/Views/CreditCardUpdateView.purs
> Fix credit card update view hangs when user has more than one card

- apps/app-article/src/App.js
- apps/app-article/src/components/header.js
Make article rendering abit smoother!
> do not show other elements unless loading is finished

- packages.dhall
> Remove a dhall "with" statement used in development

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Types.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Helpers.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Types.purs
- packages/components/src/DatePicker/Component.purs
- packages/components/src/DeliveryReclamation.purs
- packages/components/src/Helpers.purs
- packages/components/src/PauseSubscription/Component.purs
- packages/components/src/Persona.purs
- packages/components/src/Profile/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
- packages/components/src/Tracking.purs
- packages/user/src/User/User.purs
> Use Data.Date instead of Data.DateTime for pure dates

- apps/mitt-konto/src/MittKonto/Main/Views/CreditCardUpdateView.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- packages/components/src/Api/Subscription.purs
- packages/components/src/DeliveryReclamation.purs
- packages/components/src/PauseSubscription/Component.purs
- packages/components/src/Persona.purs
- packages/components/src/Search.purs
- packages/components/src/TemporaryAddressChange/Component.purs
- packages/components/src/Tracking.js
- packages/components/src/Tracking.purs
- packages/user/src/User/User.purs
> Add Subsno type

- apps/mitt-konto/src/MittKonto/Main/Views/CreditCardUpdateView.purs
- packages/components/src/Bottega.purs
- packages/user/package.json
- packages/user/src/User/User.purs
- packages/vetrina/package.json
- yarn.lock
> Use simplified workflow for updating a credit card

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Views/LoginView.purs
> Use one function to set user to state

- apps/mosaico/src/Article/Article.purs
- apps/mosaico/web/index.html
- less/mosaico/article.less
- packages/components/src/Lettera/Models.purs
- Add preamble to article view
> Add preamble

- apps/app-article/src/components/article-content.js
linkpulse uses this identifier to track scrolling
> add linkpulse identifier to content

- apps/mitt-konto/src/MittKonto/Main/Views/UserView.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription.purs
- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- apps/mitt-konto/test/Payment.purs
- apps/mitt-konto/test/Subscription.purs
- apps/mitt-konto/test/Test.purs
- less/Profile.less
- less/Subscription.less
- packages/components/src/Grid.purs
- packages/test/src/Puppeteer.purs
Remove "Ingen tidning" section, add "Ändra" button for editing
subscription pauses and temp address changes and other style updates.
Also fix the test suite.
> UI updates to Mitt Konto

- Makefile
- ci/README.md
- package.json
- yarn.lock
> Add functionality to generate ci yamls locally

- apps/app-article/src/App.js
- apps/app-article/src/components/article-content.js
- apps/app-article/src/components/footer.js
- apps/app-article/src/index.css
Small dark mode style issues fixed
> Dark mode small fixes

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
This reverts commit 167f0e8a0aea098dd4403e7101e751c8b1e2ed42.
> Revert "Deploy maintenance page (#683)"

- apps/app-article/src/App.js
- apps/app-article/src/index.css
Fix for dark mode issues premium section view inside article
> Fix more dark mode style issues

- packages/components/src/Profile/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
- packages/components/src/ValidatableForm.purs
> Validate Finnish zip codes to be exactly five numbers

- packages/components/src/DatePicker/Component.purs
- packages/components/src/PauseSubscription/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
Using activeStartDate broke changing the month.
> Use defaultActiveStartDate, not activeStartDate with date picker

- apps/app-article-server/src/server/index.js
This makes things nicer and a bit faster too.
> Make http requests asynchronous

- less/TemporaryAddressChange.less
- packages/components/src/CountryDropDown.purs
- packages/components/src/Profile/Component.purs
- packages/components/src/TemporaryAddressChange/Component.purs
Add note about changing country to temporary address change as well
> Add note about changing country to temp address change

- apps/mosaico/src/Mosaico/Header.purs
- apps/mosaico/src/Mosaico/Header/Menu.purs
- less/mosaico/header.less
- less/mosaico/header/menu.less
- yarn.lock
* Make the menu content layout explicit
* Use data sctructure to describe a menu section
* Move grid layout positions to less
* Wrap a section with its subsections in a single element to position in grid
> Refactor Mosaico.Header.Menu

- apps/mosaico/spago.dhall
- apps/mosaico/src/Main.purs
only handling the 404, not returning a whole page.
the recommended way to handle a 404 as recommended by the author:
https://github.com/hoodunit/purescript-payload/issues/6
> add 404 response to the server

- apps/mosaico/src/Main.js
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/Error.purs
- apps/mosaico/src/Mosaico/Frontpage.purs
- apps/mosaico/src/Mosaico/StaticPage.purs
- apps/mosaico/src/MosaicoServer.purs
- apps/mosaico/web/index.js
add static page route to backend router.
add error module for showing if something went wrong and page needs to be reloaded.
> add static page route to backend router

- apps/mosaico/spago.dhall
- apps/mosaico/src/Main.js
- apps/mosaico/src/Main.purs
- packages/components/src/Lettera/Models.purs
The FFI was getting messy. Let's just have one function where we append stuff to `<head>`.
Also we should help out [purescript-cheerio](https://pursuit.purescript.org/packages/purescript-cheerio/0.2.4) in implementing `append` 🙂
> Create general purpose fn to append template head

- apps/app-article-server/src/browser/components/article.js
- apps/app-article-server/src/browser/index.html
- apps/app-article-server/src/browser/index.js
- apps/app-article-server/src/server/index.js
Get most read articles in the browser instead of in the server.
Also lots of prettier noise.
> Most read lists request in browser

- apps/mosaico/spago.dhall
- apps/mosaico/src/Article/Article.js
- apps/mosaico/src/Article/Article.purs
- apps/mosaico/web/index.html
- packages/components/src/Lettera/Models.purs
- packages/user/src/User/Login.purs
> Evaluate external js got from Lettera

- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/Header.purs
- apps/mosaico/src/Mosaico/Header/Menu.purs
- less/mosaico/header.less
- less/mosaico/header/menu.less
It seems or some categories, for instance teater, Lettera will not return anything. The queries must be fixed there.
> Read menu page categories from Lettera

- .github/workflows/previews.yml
- .github/workflows/production.yml
- apps/app-article-server/package.json
- apps/app-article/package.json
- apps/hbl365/package.json
- apps/mitt-konto/package.json
- apps/mosaico/package.json
- apps/prenumerera/package.json
- ci/app-servers/app-article-server.dhall
- ci/app-servers/mosaico-server.dhall
Also remove redundant persona and lettera urls from app engine builds.
> Remove source maps

- apps/app-article-server/src/browser/components/article-additional.js
- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/components/article-details.js
- apps/app-article-server/src/browser/components/article.js
- apps/app-article-server/src/browser/components/badge.js
- apps/app-article-server/src/browser/components/header.js
- apps/app-article-server/src/browser/index.css
- apps/app-article/src/config.js
- apps/app-article/src/index.css
- yarn.lock
- Use classes for setting correct font-sizes
- Add missing parameters to badge
> Font-size tweaks, add missing badge to premium articles

- apps/app-article-server/src/browser/index.css
- Line-height fixes in headlines
> fix: headline line-heights

- apps/mosaico/src/Article/Article.purs
- packages/components/src/Lettera/Models.purs
Still needs an update to Lettera first.
> Add removeAds field to V4 articles

- apps/mosaico/src/Article/Article.purs
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- less/mosaico/article.less
The font in article stubs will still need to be checked.
> Add most read articles after articles

- apps/mosaico/static/kontakt.html
- less/mosaico.less
- less/mosaico/static-pages/kontakt.less
-add html and less files for contact page
-make layout for mobile view according to current page (tablet/desktop view not included so far)
-embed google form via iframe (and dislike it) just to see if it works and how it behaves
> add contact page to static pages

- apps/mosaico/static/kundservice.html
- less/mosaico.less
- less/mosaico/static-pages/kundservice.less
-add html & less file for customer service static page
-mobile layout (draft) so far only, tablet/desktop still to be done
> add mobile layout for kundservice page

- apps/app-article-server/src/browser/ads.txt
We have hired Relevant (relevant.fi) to build programmatic ads for us, and these changes are needed to enable their programmatic ads to work.
> Update ads.txt for app-article-server to same as for sites

- apps/app-article-server/.env
- apps/app-article-server/README.md
- apps/mosaico/.env
- apps/mosaico/README.md
Adds gzip compression to spa artifacts uploaded to gcs
> Spa compression support

- .gitlab-ci.yml
- deploy.rb
> upload spa artifacts in deploy tasks

- apps/mosaico/src/Mosaico/Header.purs
- less/mosaico/header.less
Fixes https://trello.com/c/owS8SFTv
> Kundservice & Prenumerera header links

- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/components/article.js
This can be tested using this line item in Google Ad Manager: https://admanager.google.com/21664538223#delivery/line_item/detail/line_item_id=5958873786&order_id=2942649353&li_tab=settings&sort_by=ComputedStatusRank&sort_asc=false
(Also switch to test key-value)
> Remove ads from advertorials (in apps)

- apps/mosaico/src/Mosaico/Header/Menu.purs
- images/icon-mosaico-epaper.svg
- less/mosaico/header/menu.less
@kaol Please check our PureScript. No need to worry about the CSS too much. :)
> Align menu and add icons

- apps/mosaico/src/Mosaico.purs
Disables mosaico-wide ads if:
- state has an article that says `removeAds = true`
- state has an article that has the type `Advertorial`
The ads are enabled when navigating to category pages and what not.
> Disable advertorial ads

- apps/mosaico/src/Mosaico.purs
- Hide ads on menu route (https://trello.com/c/7CAKP7ZY/665-hide-parad-ad-on-menu-route)
- Hide ads on static page routes (as disqussed in some review&planning session)
> Hide ads on menu and static page routes

- apps/mosaico/web/index.html
> Update dredition css

- apps/mosaico/src/Article/Image.purs
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
Also:
- don't show ads in drafts
- don't render image caption if no caption
> Recognize draft advertorials

- apps/mosaico/src/Article/Image.purs
- less/mosaico/article.less
The 'close button' is shown in the top right corner of the screen, unfortunately not on top of the img, as the image can be resized.
> Add caption + 'close button' for fullscreen images

- apps/app-article/package.json
- apps/mosaico/package.json
- apps/mosaico/src/Mosaico.js
- apps/mosaico/src/Mosaico.purs
- packages/components/src/Sentry.js
- packages/components/src/Sentry.purs
- packages/vetrina/package.json
- yarn.lock
Let's share one sentry project for all papers, as it's the same app anyway. We can separate the sites by adding a tag.
> Add sentry to mosaico

- less/mosaico/article-list.less
- less/mosaico/article.less
- less/mosaico/components/profile.less
- less/mosaico/header.less
* Add max-width to fullscreen images
* Horizontally center article lists in tablet/medium
* Make profile page less ugly
* Vertically center logo on mobile sized static header
> Fix stylings

- apps/mosaico/static/bruksvillkor.js
- apps/mosaico/static/fragor-och-svar.js
- apps/mosaico/static/kontakt.js
- apps/mosaico/static/tipsa-oss.js
Also: when navigating to anchors, append the state to the history so the back button is not broken.
> Initialize static page JS only once

- less/mosaico/footer.less
> Add top padding to footer

- less/Vetrina.less
> Make vetrina checkbox larger

- apps/mosaico/src/Mosaico/Footer.purs
Street name is Lund**a**gatan
Also, Robin asked for a line break before **På onsdagar...**
> Fix footer ÖN adress

- apps/mosaico/src/Mosaico/Footer.purs
Minor text change to ÖN footer requested by Pernilla Karlsson
> Add some info to ÖN footer

- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico/Epaper.purs
- apps/mosaico/src/Mosaico/Header.purs
- apps/mosaico/src/Mosaico/Header/Menu.purs
- apps/mosaico/src/Mosaico/Routes.purs
Add trailing slash to epaper URL
> Use Prenumerera link on epaper latest image if not entitled

- apps/mosaico/src/Mosaico.purs
> De-state Mosaico variable in Mosaico

- less/Vetrina.less
> Add a margin after the Vetrina box

- apps/mosaico/web/index.js
- Move around some content units according to wishes from the sales department.
> Fix ads according to feedback from sales department.

- apps/mosaico/web/index.js
- less/mosaico/ads.less
- Make Mobparad work like Maxparad for creative templates in Google Ad Manager.
- Make it clickable-to-close like Maxparad.
> Make Mobparad accept creative template like Maxparad

- less/mosaico/components/epaper.less
> Add missing epaper liftup styles

- apps/mosaico/web/index.js
Yes, this is a horrible change.
> Workaround slow analytics

- apps/mosaico/web/index.html
> Update Aptoma frontpage css

- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/Feed.purs
- packages/components/src/Lettera/Models.purs
Collect window variables as Json values instead of encoding them as
Strings first
> Use server loaded article as clickedArticle in initial Mosaico state

- apps/mosaico/web/index.html
> Update Aptoma front page css

- apps/app-article-server/package.json
- yarn.lock
semver, why dou you suck so much...
> pin cheerio to 1.0.0-rc9 in app-article-server

- apps/mosaico/src/Main.purs
- packages/components/src/Registration/Component.purs
- packages/components/src/ValidatableForm.purs
Uncapitalize "e-postadress" in two messages
> Add image-preview-size robots meta tag

- apps/mosaico/src/Mosaico/LoginModal.purs
- less/mosaico/components/epaper.less
TW reset all h_ styles, this fixes the two places relying on browser
defaults.
> Fix header styling

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
This reverts commit de4bd66d54c4b825d2e7c719e2d96911f31d59f7.
> Revert "Enable maintenance mode (#1353)"

- apps/prenumerera/src/Page/Register.purs
Related [trello issue](https://trello.com/c/U483Xufn/1305-update-customer-service-hours-on-prenumerera)
> Update CS info in prenumerera loginpage

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
- static/maintenance.html
This reverts commit f99c9eeb7a3c8fb87c016022d159f99fd60d7b1e.
> Revert "Enable maintenance mode (#1367)"

- packages/components/src/Sentry.js
https://developers.facebook.com/community/threads/320013549791141/
> Ignore an error caused by buggy Instagram browser

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/container.dhall
- ci/workflows.dhall
- package.json
fix permission issues with CI check job
> Use newer build image with node 16

- .gitlab-ci.yml
This also updates the "clientside" vars for lettera url to v4, this should work until I fix the infra side of things and remove this custom "hackjob" I made to accomodate v3 and v4 urls.
> update the spa side urls to v4

- .gitlab-ci.yml
This should fix the current build issues with app-article-server
> Revert to old diskho

- apps/mitt-konto/src/Components/Paywall.purs
- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Views.purs
- apps/mitt-konto/src/MittKonto/Routes.purs
- packages/components/src/Api/Entitlements.purs
- packages/components/src/Persona.js
- packages/components/src/Persona.purs
- packages/user/src/User/User.purs
Add a new page for managing paywall openings
> First attempt at creating a paywall disabling button

- apps/mitt-konto/src/Components/Paywall.purs
- packages/components/src/Api/Entitlements.purs
- packages/user/src/User/User.purs
Relates to https://trello.com/c/kgxOpoxg/1542-ability-to-add-future-paywall-openings-for-mitt-konto-admins
> Make it possible to open paywall in future

- apps/app-article-server/src/browser/index.css
This broke because of https://github.com/KSF-Media/affresco/pull/1458
> Fix advertorial liftup colors

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
> Remove hbl365 from CI

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
This reverts commit 78055b156435c5aa7a04b28f8fa555474142b532.
> Revert "Enable maintenance mode (#1484)"

- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/index.css
https://trello.com/c/snRNT62x/1647-styling-for-tables-in-mosaico-and-app-article-server
> Render and style tables from tables plugin in app-article-server

- packages/user/src/User/Login.purs
See https://trello.com/c/0BlGSfss/1706-inform-users-on-login-screen-that-google-login-will-end-at-end-of-year
> Inform users about the end of Google login

- apps/app-article-server/src/browser/components/article.js
https://trello.com/c/4j7RwOCd/1720-improve-embedding-of-dn-graphics-in-app-article-server-automatic-height
> Listen for and set height of DN graphics embed in app-article-server

- packages/vetrina/src/Vetrina/Products/Premium.js
- packages/vetrina/src/Vetrina/Products/Premium.purs
reads `HBL_CAMPNO`, `VN_CAMPNO` and `ON_CAMPNO` variables for the current active campaigns
> Make campaign numbers configurable from env

- apps/prenumerera/src/Package/Description.purs
- apps/prenumerera/src/Package/Group.purs
See https://trello.com/c/xaOGYTzC/1723-add-small-disclaimer-to-prenumerera-about-coming-price-changes
> Add disclaimers for upcoming price increases for certain packages

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
- static/maintenance.html
Reverts KSF-Media/affresco#1533
> Revert "Enable mmode for prenumerera & mitt-konto"
