- packages/ksf-login/src/JanrainSSO.purs
- packages/ksf-login/src/KSF/Login/Component.purs
the `end_session` method of SDK takes a callback that will be called upon the completion and does stuff asynchronously. So far we've been calling it with a no-op callback and proceeding with the normal flow.
Under slow network this created a gnarly race condition. The `end_session` would start executing (but veeeery slowly), while the app proceeds and switches back to the login screen. This causes the `check_session` to be triggered again, which picks up the still alive SSO session (`end_session` is still blocked on network) and log the user back in. BUM.
Here, I wrap the `end_session` in an aff, which allows us to conveniently "block" on it, and proceed with logout flow only after the SSO logout has been carried.
> Make JanrainSSO.endSession async (so that it waits for completion)

- packages/ksf-login/src/KSF/Login/Component.purs
- packages/ksf-login/src/KSF/Login/Google/Google.js
- packages/ksf-login/src/KSF/Login/Google/Google.purs
- psc-package.json
This is to fix the same bug as in #17
I would have loved to handle the rest of Google SDK in the same way, but probably later, along with stopping using `attachClickHandler`.
> Make Google.logOut return an Aff

- apps/mitt-konto/src/MittKonto/Main.purs
- packages/ksf-login/src/KSF/Login/Component.purs
This does the timeouting and prevents the spinner for staying indefinitely, but doesn't show anything to the user. Doing that will be a part of #7
Fixes #6
> Timeout long running actions, so user doesn't get stuck with spinner

- packages/ksf-login/src/JanrainSSO.js
I've read Janrain's sso source and figured out that there is a way to
enable debugging output. Weirdly enough it seems to fix #22 for
me (both in Firefox and Chrome).
I'm not really trusting such fix, but I thought that it's a good
idea to commit it and try on staging. It won't hurt to have debug
logs either way.
> Enable SSO debug logs

- packages/ksf-button/src/KSF/Button/Component.purs
I don't yet know the exact reason for it, but I started getting the following error that prevents the application from loading at all:
It comes from the our button component that tries to find it's DOM node on the first mount and throws the exception if it's not found. To be on the safe side, I've replaced the throw with logging.
The only reason that we need the button's DOM node is because we are using [`attachClickHandler`](https://developers.google.com/identity/sign-in/web/reference#googleauthattachclickhandlercontainer-options--onsuccess-onfailure) method of Google SDK. It simply takes a pointer to a `div` element of a social-login button and does all the stuff when the user clicks it. We've copied this approach from existing social-login implementation in prenumerera.
It's also …
> Don't throw an error when the <Button> node is not found

- packages/ksf-login/src/KSF/Login/Component.purs
This prevents Janrain SSO logout from hanging.
> Call Janrain checkSession before logging out

- packages/ksf-login/src/KSF/Login/Component.purs
- packages/ksf-login/src/KSF/Login/Login.purs
- packages/ksf-login/src/KSF/Login/View.purs
- packages/persona/src/Persona.purs
Catches internal server errors from Persona. Shows a simple error message to the user above the login form.
Fixes #14
~~TODO:~~
~~Add callback from parent~~
> Login internal server error handling

- apps/mitt-konto/resources/mitt-konto.less
- apps/mitt-konto/src/MittKonto/Main.purs
- build-purs.rb
- less/Alert.less
- less/ksf-colors.less
- packages/ksf-alert/package.json
- packages/ksf-alert/src/KSF/Alert/Alert.less
- packages/ksf-alert/src/KSF/Alert/Component.js
- packages/ksf-alert/src/KSF/Alert/Component.purs
- packages/persona/src/Persona.js
- packages/persona/src/Persona.purs
> Catch and display global errors in mitt-konto

- packages/ksf-login/src/KSF/Login/Facebook/Sdk.js
If the Facebook SDK is already loaded to the site, loading and initializing it the second time will cause the SDK to break.
Fixes #44
> Check for FB object before loading Facebook SDK

- deploy.rb
I only added `elections` to a list of `apps`. The script would have
failed if any of the `env_variables` weren't defined. We don't need
any of existing variables in the `elections`, but we'll soon need some
other ones (the backend URL I suppose).
Instead of having a list of `apps` and a global list of
`env_variables` I made an object where app names are keys
and their env variables are in the values (possibly with
some other configuration in the future).
TIL ruby, WAAAAAT :D
> Add elections to deploy.rb, restructure env_variables

- packages/ksf-login/src/JanrainSSO.js
- packages/ksf-login/src/JanrainSSO.purs
- packages/ksf-login/src/KSF/Login/Component.purs
The `window.JANRAIN` won't be defined then and we shouldn't be trying to do anything with it.
> ksf-login: handle the situation in which sso library is not loaded

- apps/app-article/src/App.js
- apps/app-article/src/index.html
- apps/mitt-konto/index.html
- apps/mitt-konto/mittKonto.js
- deploy.rb
- lerna.json
- package.json
We don't need it in the end, because of Yarn workspaces.
> Remove lerna

- packages/ksf-login/src/JanrainSSO.purs
- packages/ksf-login/src/KSF/Login/Component.purs
This way it's impossible to call those functions without having a
config, and the only way to get a config is by calling a function
`loadConfig :: Effect (Maybe Config)` which will ensure that the
library is loaded.
> Require JanrainSSO.Config in all the functions that call to SSO

- README.md
- package.json
Adds `uglify-js` for minifying javascript on deploy.
The deploy minifies javascript files under `script/`. For each js file, the deploy creates a file called `xxxx.min.js` to the same directory where the original file is.
> Add uglify-js

- scripts/app/gamAppAds.js
Added a new method to the ksfDfp object. The method ksfDfp.startUp() will run the ads code. In a web environment the script is started automatically when the DOM state becomes interactive or complete. This does not work here because React runs in a similar fashion and there is no knowing which of them will be ready first.
> Ads now load only when asked to.

- apps/app-article/src/index.css
To make double sure there is no sideways scrolling an overflow-x is in place. Also removing that pesky height form the iframe. It somehow sneaked back into the index.css.
> Prevent overflow in article container

- deploy.rb
- static/maintenance.html
Whenever running the deploy script as such, `ruby deploy.rb mitt-konto --maintenance`, a maintenance page is showed.
> Add possibility to deploy a maintenance page

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina/.build-size-sha256
- packages/user/src/User/Login.purs
- packages/user/src/User/Login/Google/Google.js
- packages/user/src/User/Login/Google/Google.purs
> Quickfix for the change of internal GoogleUser structure

- apps/mitt-konto/.build-size-sha256
- apps/prenumerera/.build-size-sha256
- apps/vetrina/.build-size-sha256
- apps/vetrina/src/Vetrina/Main.purs
- apps/vetrina/src/Vetrina/Purchase/Completed.purs
- packages/components/src/Api.purs
- packages/components/src/Persona.purs
- packages/components/src/Spinner.purs
- packages/user/src/User/Login.purs
- packages/user/src/User/User.purs
This was just a problem of casing against `props.user` instead of `state.user` (#297). Fixed a couple of other things as well:
- add CacheControl header to the `getUser` call -> we need to fetch a fresh user when mounting Vetrina
- add loading spinner when setting the password
- actually send the `confirmPassword` value to the server
> Hide set password form when user already set the password

- apps/mitt-konto/.build-size-sha256
- apps/mitt-konto/.env.development
- apps/mitt-konto/src/MittKonto/Main.js
- apps/mitt-konto/src/MittKonto/Main.purs
- packages/components/src/Api/Subscription.purs
- packages/components/src/Error.purs
- packages/components/src/JSError.js
- packages/components/src/JSError.purs
- packages/components/src/Persona.purs
- packages/components/src/Profile/Component.purs
- packages/components/src/Subscription/Component.purs
- packages/user/src/User/User.purs
Will send Sentry events on
- logging in errors
- fetching user errors
- subscription action errors (pause, temporary address change, delivery reclamation)
- profile name and address errors
Also ditched `React.Compat` from `MittKonto`. Oh, also separated `Subscription` from `Persona`.
Fix #303
> Add Sentry to mitt-konto

- apps/mitt-konto/.build-size-sha256
- apps/mitt-konto/src/MittKonto/Main.purs
- packages/components/src/Sentry.js
- packages/components/src/Sentry.purs
Only send error events when SomethingWentWrong or UnexpectedError
Remove Sentry user when logging out
> Adjust Sentry levels

- scripts/app/gamAppAds.js
The script wont build. It seems that our build script cannot understand let. Changed to var.
```
Parse error at scripts/app/gamAppAds.js:188,20
12:53:26 PM:                 let unclosed = headerToClose.length - 1;
12:53:26 PM:    
```                 ^
> script wont build because of let. changed to var.

- apps/app-article/src/index.html
Chrome sometimes fails to move the whole ad and creates an empty box. This is almost certainly a timing issue. Works faultlessly in Safari and mostly in FF. Must rework the mover functionality to be within the main ad script, that will proof it from timing issues.
> disable mover script as it fails sometimes in Chrome

- apps/vetrina-staging/.build-size-sha256
- packages/vetrina/README.md
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Vetrina.purs
> Add external JSX rendering to Vetrina component

- apps/podcasts/src/App.js
- apps/podcasts/src/less/main.less
Some tweaking, mainly the menu layout.
Old layout:
Changed to:
> Podcasts: more responsive menu layout

- apps/vetrina-staging/.build-size-sha256
- less/Vetrina.less
- packages/vetrina/package.json
- packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs
When the user is logged in but has no firstname defined, the landing page of vetrina might be a bit confusing. So let's show their email address there.
> Show user email in landing view if firstname is not present

- packages/article/src/Article/RecordToSum.purs
Note: this is extracted from [this commit](https://github.com/KSF-Media/affresco/commit/b3e0654e93f8a3f9169ccfe645d87e743e484830), where you can see it in use.
One of the problems we have is that the Lettera API encodes our `BodyElement` sum type as a record with `Nullable` fields.
So e.g. if we have this type:
```haskell
data Element = Html Text | Image Image | ...etc
```
..on the frontend we could be getting
```json
{ "html": "whatever" }
```
or
```json
{ "image": { "url": "..", "etc" }}
```
and so on.
Now, we can model this with a record containing `Nullable` fields:
```purs
type BodyElement =
{ html :: Nullable String
, image :: Nullable Image
, ...
}
```
..and then try to find which field we have at every given time, and kind of match on that.
This is very uncomfortable, so this PR …
> Add generic decoding of records of `Nullable` fields into sum types

- apps/app-article/src/App.js
- apps/app-article/src/index.css
- scripts/app/gamAppAds.js
Some major changes to how in text ads are handled. Some code in App.js was removed and replaced with a function that checks paragraphs to see if they are appropriate for ad placement. There are two ad slots placed, DIGIHELMOB and MOBMITT. The MOBMITT was mostly failing to get placed with the old code. The code placing DIGIHELMOB was previously in the external ads script and suffered from some timing issues. The placement code is now removed from the external script and that script is now run after the slots have been placed, from App.js.
Note that both the App.js and the external ad script must be updated for this to work, so caching issues might cause problems.
> In text ad refactoring

- apps/app-article/src/article-service.js
We want to exclusively show subscriber data for the most read list in the app article in HBL Nyheter. The other news apps can use all most read data.
> Add subscriber mostread for HBL in app article

- apps/mitt-konto/src/MittKonto/AccountEdit.purs
- packages/components/src/Api/Error.purs
- packages/components/src/Bottega.purs
- packages/components/src/CreditCard/Update.purs
- packages/components/src/Persona.purs
- packages/user/src/User/User.purs
- packages/vetrina/src/Vetrina/Vetrina.purs
Instead of returning just a `String` every time we encounter an error from Bottega, add a proper type for that. This PR adds one constructor to that type 😅 However, we should add constructors to this when/if needed.
The main purpose here is to catch the `missing_address_details` error, so we can show the address form in Vetrina.
> Better bottega errors

- apps/mitt-konto/src/MittKonto/IconAction.purs
- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Views/PaymentView.purs
- apps/prenumerera/src/Prenumerera/Confirm.purs
- apps/prenumerera/src/Prenumerera/Main.purs
- apps/prenumerera/src/Prenumerera/PaymentSelect.purs
- apps/prenumerera/src/Prenumerera/ProductSelect.purs
- apps/prenumerera/src/Prenumerera/User.purs
- packages.dhall
- packages/components/src/Navbar/Component.purs
- yarn.lock
Here's the counterpart for using the updated react-basic-router library. Most of the changes are simply that `element` calls are dropped.
I'm surprised about the changes needed for Prenumerera. Looks like it somehow discarded `Nullable` from `Location` and my changes to router somehow made that `Nullable` visible to the code and it didn't type check any more.
The code now has types like `Nullable (Nullable ...)` in it but I didn't try to clean those up.
> Update purescript-react-basic-router version

- ci/dhall.nix
This should be enough to prevent building its dependencies from scratch each time.
> Bump easy-dhall-nix hash

- apps/mitt-konto/src/MittKonto/Main/Views/UserView/Subscription/Elements.purs
- packages/components/src/Api/Package.purs
- packages/components/src/Api/Subscription.purs
- packages/user/package.json
- packages/vetrina/package.json
- yarn.lock
This adds `canPause` and `canTempAddr` fields to packages data.
Reminder: Don't merge to master before deploying Persona with those fields to production.
This'll be followed by another change to actually set these fields for the affected products, but that'll be on back end.
> Allow disabling pauses and temp address changes for some package types

- apps/mitt-konto/src/MittKonto/Main.purs
- apps/mitt-konto/src/MittKonto/Main/Views/LoginView.purs
- apps/mosaico/src/Mosaico/LoginModal.purs
- packages/user/src/User/Login.purs
Let's move the magic login responsibility (the automatic logging in if uuid + token are found in local storage) to the client of Login component rather than have it in the Login itself.
Because if you think about it, if we already have the user, it makes no sense to mount the Login component in the first place. 
Also rename the `launchAff_` prop of Login to `onLogin`.
> Remove magic login attempt from Login component

- apps/mitt-konto/src/MittKonto/Main.purs
- packages/components/src/Search.purs
This is disgusting and I wouldn't be doing it this way if this wasn't for internal use.
Just using `setHref` will reload the page and discard any personation. Pushing or replacing state with History API will change the address in the address bar but React will not react to that change. I don't think this could be done with any `Router.Link` on the button either since getting the user to personate is an `Aff` and not an `Effect`.
If you have an better idea about how to do this then I'm open to it.
> Simulate click to directly view as customer

- apps/hbl365/src/Main.js
- apps/hbl365/src/Main.purs
- less/HBL365.less
I couldn't think of a native PureScript way of doing this. The only onscroll handling code I saw was in Halogen and we don't use it.
> Add onscroll handler for adding header.tight in HBL365

- apps/mosaico/src/Article/Article.purs
It would be unusual to move from article stub to a missing article, so defaulting to show the premium/share icons row would make more sense.
> Show premium/share icons row for article stubs

- apps/mosaico/src/Mosaico.purs
This prevents first loads of category pages from flashing 404 page
> Use categoryStructure to set Mosaico initial route value

- less/mosaico/static-pages/bruksvillkor.less
- less/mosaico/static-pages/fragor-och-svar.less
- less/mosaico/static-pages/kundservice.less
- less/mosaico/static-pages/static-page.less
-for all static pages correct line-height by removing unit from line-height
-delete redundant line-height-rules
-remove justification for terms and conditions text
> change line-height to correct value & remove unit

- apps/mosaico/src/Main.js
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico/Feed.purs
- apps/mosaico/web/index.html
Also retain the same Cheerio template for all content appends and only
serialize it to HTML when done.
> Restore HTML feed to vars and move them after rendered HTML

- less/mosaico/_grid.less
The Aptoma article preview puts a grey background on the iframe Mosaico is embedded in. Let's set the Mosaico bg to white for a more WYSIWYG experience.
> Make backgound white to override preview bg

- less/mosaico/article.less
When the sidebar is taller than the main article content, the metabyline gets steched out. I added a `grid-template-rows` property to fix that.
See https://trello.com/c/GfWnMAJn/672-metabyline-takes-too-much-space for details.
> Fix article main grid

- apps/app-article-server/src/browser/components/article-content.js
- Adds a check for darkmode in article-content.js to fix darkmode.
`<h4 className={`headline headline-question ${this.props.darkModeEnabled ? "darkMode" : ""}`} key={key}>`
> Fix headline question to show darkmode

- .github/workflows/previews.yml
- .github/workflows/production.yml
- ci/apps.dhall
- ci/ci-master.dhall
- ci/workflows.dhall
also pins all action "imports" to a version instead of `master` or `main`
> Remove mosaico from list of production apps

- apps/mosaico/src/Mosaico.purs
After moving the ad refreshing code inside the `routeListener`, it was still left in the previous place in the `simpleRoute` function by mistake. This caused ad slots to be refreshed twice on route changes and chrome started to throw a bunch of warnings and displaying some weird ad behaviour.
> Remove duplicate refreshing of ad slots

- apps/mosaico/src/Main.purs
Now accepts trailing slashes and in fact whatever path you give it. Will use the first segment as article id or title slug.
> Make /artikel endpoint more lenient

- apps/mosaico/src/Mosaico/Profile.purs
Can't be tested on localhost. We should check once it's on Staging.
So clicking on "Hantera dataskydd" should open the GDPR message (on Staging):
> Open GDPR consent message on click in Account

- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/Webview.purs
According to SO postings, other people are also having trouble with
video.js when not loading the page fully.  So let's skip using router
for that and just use the a href as is.
Also, this enables autoplay for torgkamera.
> Bypass router and use plain old link to go to webview categories

- less/mosaico/article.less
- less/mosaico/components/box.less
- Make article header css more specific so it doesn't affect the fact box header
- Make expanded fact box body font same as non-expanded
- Increase fact box header font-size a bit
(article to test with: /artikel/23b8c2ce-b5fb-4298-a8a8-6fbf4abb866e)
> Fix facbox header and body font

- apps/mosaico/web/index.js
- Give Digihelmob same target ID as Digihel
- Remove redundant (is it???) Digihelmob slot listed under desktop slots.
> Give Digihelmob same target ID as Digihel

- apps/mosaico/.env.local
- apps/mosaico/src/Article/Advertorial/Basic.purs
- apps/mosaico/src/Article/Advertorial/Standard.purs
- apps/mosaico/src/Article/Article.purs
- apps/mosaico/src/Article/Box.purs
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/test/Main.purs
- less/mosaico/article.less
- less/mosaico/components/box.less
- packages/components/src/Lettera/Models.purs
Update Mosaico.Article.Box from React Classic to Hooks style and
remove paper property from it and instead use the ancestor's paper
specific id to select brand colors.
Make Advertorial Standard and Basic components into proper components
and move Image and Box components from Mosaico to them.
> Use box block type parameter and add styles for review box

- apps/mosaico/.env.test
- apps/mosaico/src/Main.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/Search.purs
- apps/mosaico/test/Search.purs
> Show 'inga resultat' as the page header if there are no results

- apps/mosaico/src/Article/Image.purs
We are currently returning `string(...)` from lettera for captions, so I also changed it to just render strings rather than html. No idea if there are articles using free-form html in captions.
> Show image captions even if either byline or caption is missing

- less/mosaico/article.less
- Use text-decoration instead of border-bottom because it renders closer to the text, make underline 2 px thick.
Fixes https://trello.com/c/oUV9TSdU/676-links-make-the-underlining-to-be-2-px-and-move-it-closer-to-the-link-text
> Make link underline thicker and move it closer to text

- less/mosaico/article-list.less
VN/ÖN front page: Always 5
HBL front page: 10 on desktop, 5 on mobile
All papers, in articles: Always 10
> Apply more rules for showing last 5 of most read and latest lists

- apps/app-article-server/.npmrc
- apps/app-article/.npmrc
- apps/corona-banner/.npmrc
- apps/duellen/.npmrc
- apps/elections/.npmrc
- apps/hbl365/.npmrc
- apps/mitt-konto/.npmrc
- apps/mosaico/.npmrc
- apps/podcasts/.npmrc
- apps/prenumerera/.npmrc
- apps/vetrina-test/.npmrc
- packages/user/.npmrc
- packages/vetrina/.npmrc
This is because npm --prefix for some reason ignores workspace-level .npmrc.
> Add .npmrc with legacy-peer-deps for every project

- packages/components/src/Lettera/Models.purs
This allows better debug printing with eg.
```
diff --git a/apps/mosaico/src/Article/Article.purs b/apps/mosaico/src/Article/Article.purs
index 8b797375..171ee943 100644
--- a/apps/mosaico/src/Article/Article.purs
+++ b/apps/mosaico/src/Article/Article.purs
@@ -33,6 +33,7 @@ import React.Basic.DOM as DOM
import React.Basic.Events (EventHandler)
import React.Basic.Hooks as React
import React.Basic.Hooks (Component)
+import Debug
isPremium :: Either ArticleStub FullArticle -> Boolean
isPremium = either _.premium _.article.premium
@@ -82,7 +83,7 @@ component = do
pure $ render imageComponent boxComponent props
render :: (Image.Props -> JSX) -> (Box.Props -> JSX) -> Props -> JSX
-render imageComponent boxComponent props =
+render imageComponent boxComponent props = trace (show props.article) …
```
> Add generic show instances for lettera models for easier debugging

- apps/mosaico/src/Mosaico/Header.purs
- apps/mosaico/src/MosaicoServer.purs
During SSR, the server actually returns two separators instead of one.
> Remove doubled header separator

- apps/mosaico/src/Article/Advertorial/Basic.purs
- apps/mosaico/src/Article/Article.purs
This change makes our article pages more semantic, and makes it easier for eg @mfahler9 to target the last article element like this:
```
$$(".article-content > .article-element:last-child")
```
> Group article content for easier targeting

- apps/mosaico/src/Mosaico/Eval.js
https://esbuild.github.io/content-types/#direct-eval
As far as I see, this doesn't affect the actually compiled/minified code (which is ...actually interesting, as the code using `eval()` should have a bunch of non-minified identifiers), and silences the warning.
> Remove direct eval call

- apps/mosaico/src/Article/Article.purs
- apps/mosaico/src/Mosaico.purs
- apps/mosaico/src/Mosaico/EpaperBanner.purs
- apps/mosaico/src/Mosaico/Frontpage.purs
- apps/mosaico/src/Mosaico/Header.purs
- apps/mosaico/src/Mosaico/Lists/LatestList.purs
- apps/mosaico/src/Mosaico/Lists/MostReadList.purs
- apps/mosaico/src/Mosaico/LoginModal.purs
- apps/mosaico/src/MosaicoServer.purs
- apps/mosaico/test/Lettera.purs
- apps/mosaico/test/Search.purs
- less/mosaico/article-list.less
- less/mosaico/components/epaper.less
This makes the following changes:
- every page has exactly one `<h1>` element. Usually article title, but defaults to a sr-only title in the header with the paper name if there are no other options.
- All headings follow consistent numbering, so you won't go from h3 to h6.
> Make headings consistent

- less/mosaico/aptoma.less
When loading (or when browsing without Javascript), the widget titles (eg. 'Box Ad 1 DESKTOP') will briefly flash before they get  replaced with whatever they are supposed to contain.
> Hide all widget titles

- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/index.css
- apps/app-article-server/src/browser/index.html
This code is currently using the same code for the GAM ad unit and the target id (`gamAndTargetId` in the code), because I got this working. So the `gamAndTargetId` will be eg
```
on/on_mobparad
vn/vn_mobparad
hbl/hbl_mobparad
...
```
I have tried switching the target id to be consistent with Mosaico (details here: https://docs.google.com/spreadsheets/d/1gWwZMC3PUNZ_UeesnVOpkgjhYoDsE6HKlsW00FMKOOQ/edit#gid=1632593384) but couldn't then get the ads to show up.
There are also a couple of #TODOS/comments in the code which need reviewing and/or changing before we merge this branch.
> New per-app ad slots for programmatic ads - wip

- apps/app-article-server/src/browser/index.css
A small bug was happening on older browser. Was using an unsupported value for overflow.
> Fix scroll bug on older browsers

- apps/app-article-server/src/browser/index.html
A key-value pair has been added to Google Ad Manager so some ads can just to targeted at the apps and not the sites. This code adds that key-value pair.
> Enable ads to be targeted at apps only

- apps/app-article-server/src/browser/index.js
https://trello.com/c/cpmbDKe6/1408-improve-placement-of-ads-in-app-article
Tweak to ad position logic to make it less likely two ads will appear in a row in the middle of an article. Currently, each ad slots into a space in between two "html" elements, but they may end up right next to each other if the first ad cannot find a suitable slot early enough. This change makes the first ad start looking for a suitable slot earlier on in the article.
> Tweak to ad position logic

- packages/components/src/InputField/InputField.purs
Add `autoFocus` prop to the **inputField** module. Allows to set a field in focus when page renders.
> Improve search

- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/index.js
- apps/app-article-server/src/server/index.js
- apps/app-article-server/src/server/insertAds.js
https://trello.com/c/Cg5scatM/1303-app-article-servers-frontend-rendering-doesnt-match-backends-rendering
Tested on the factbox in this article: http://localhost:8080/article/44f345b5-eb92-4e60-a884-26396cd3d831?paper=test  (test parameter makes test ads appear)
We've been using the array index to create keys for article items, but this has led to a mismatch between keys created before and after ads have been inserted into the article. So instead, as soon as the article has been fetched, the ad slots are inserted and a uuid-generated key is then created for each article item. The keys then don't change on render.
The factbox in the test article should open up, if the keys are in sync.
> fix out-of-sync keys caused by inserted ads

- apps/app-article-server/package.json
- apps/app-article-server/src/browser/components/article-content.js
- apps/app-article-server/src/browser/components/article.js
- apps/app-article-server/src/browser/components/mobile-article-list.js
- apps/app-article-server/src/browser/index.css
- apps/app-article-server/src/browser/index.html
- yarn.lock
What this does:
• Uses React.lazy for the most read list component (don't think this do much when we return the page from the server)
• Lazy loads all images except main header image. Uses react-lazy-load-component for this.
• Use smaller file formats for fonts, woff2 seems to have been supported for quite a while now.
• We seemed to be loading some css twice. Stopped doing that.
> Improve app article loading

- packages/components/src/Sentry.js
- packages/components/src/Sentry.purs
This will let apps define their own transaction sampling rate for Sentry as the rate required by mosaico is quite low (0.03)
> Make Sentry transactionSamplingRate configurable

- .gitlab-ci.yml
- apps/app-article-server/Dockerfile
the lts-20.5 image now pins the correct yarn version
> switch to building with lts-20.5

- packages/vetrina/src/Vetrina/Vetrina.js
- packages/vetrina/src/Vetrina/Vetrina.purs
- This will stop the page scrolling to Vetrina immediately when article is loaded. Tested with Nets test cards to make sure the autoscrolling still works in cases of failure  and such.
- Also re-wrote the scrolling function so that it takes the fixed header height into account so it doesn't overlap with Vetrina.
> No initial scroll

- packages/components/src/Helpers.purs
- packages/components/src/Lettera/Models.purs
Will be used by Mosaico to implement redirecting of /artikel/<editoriald> to published article.
> Add utilities to KSF.Helpers

- apps/app-article-server/src/browser/index.css
For reasons sometimes there are inline background colors on some links. This should remove that.
> Fix grey links again

- apps/app-article-server/src/browser/components/article-content.js
These scripts caused some weird JSON to appear at the top of the page if one of the scripts were syntactically invalid. Apparently, rendering executes the scritps. Fixes https://trello.com/c/5bRlQoNX/1558-fix-problems-encountered-in-app-article-server-migration-to-lettera-v4
> Fix/remove external scripts from most read articles in app-article-server

- packages/components/src/Sentry.js
Instead of filtering by error message filter out everything not originating from our own domains.
> Only send errors originating from our own code to sentry

- packages/vetrina/src/Tracking.js
- packages/vetrina/src/Tracking.purs
- packages/vetrina/src/Vetrina/Vetrina.purs
Added an analytics event to show that the purchase process has started.
Also, tried to make purchase event a bit more robust just in case.
Context here is that the discrepancy between paywall purchases as shown by Kayak and the number shown in web analytics has widened.
> changes to tracking

- packages/components/src/Sentry.js
This should filter out the masses of sentry errors generated by iOS devices trying to access the nonexistent telephone field of our writers.
> Add a filter for "unfixable" errors to Sentry
